on: [push, pull_request]
name: Test



env:
  GOVERSION: '1.19'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GOVERSION }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test ./...
